#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

nohup java -Xmx256m -Xms256m \
    -Djava.io.tmpdir=${OPENSHIFT_TMP_DIR} \
    -Djavax.servlet.request.encoding=UTF-8 -Dfile.encoding=UTF-8 \
    -jar ${OPENSHIFT_REPO_DIR}/jetty-runner.jar \
    --host ${OPENSHIFT_INTERNAL_IP} --port ${OPENSHIFT_INTERNAL_PORT} \
    ${OPENSHIFT_REPO_DIR}/springmvc-example.war \
    > ${OPENSHIFT_DIY_LOG_DIR}/server.log 2>&1 &
